Repository wordpress-mobile/WordPressAuthenticator-iOS, pull requests merged in 2019-09, with the labels that each got.

#125 [SIWA] Add Continue with Apple to Sign Up
  WordPressAuthenticator.podspec
  WordPressAuthenticator/Signin/LoginEmailViewController.swift
  WordPressAuthenticator/Signin/LoginPrologueSignupMethodViewController.swift
  WordPressAuthenticator/Signin/LoginPrologueViewController.swift
Labels: SIWA

#133 Adds missing signin events for SIWA
  WordPressAuthenticator.podspec
  WordPressAuthenticator/Signin/AppleAuthenticator.swift
Labels: bug

#123 Change copy per Editorial and to reflect Android app
  WordPressAuthenticator/Extensions/WPStyleGuide+Login.swift
  WordPressAuthenticator/Signin/LoginSiteAddressViewController.swift
Labels: enhancement, good first issue

#137 [SIWA] Check Apple User state
  WordPressAuthenticator.podspec
  WordPressAuthenticator/Authenticator/WordPressAuthenticator.swift
  WordPressAuthenticator/Authenticator/WordPressAuthenticatorDelegateProtocol.swift
  WordPressAuthenticator/Signin/AppleAuthenticator.swift
Labels: SIWA

#138 [SIWA] Observe Apple Credential Revoked notification
  WordPressAuthenticator.podspec
  WordPressAuthenticator/Authenticator/WordPressAuthenticator.swift
  WordPressAuthenticator/Signin/AppleAuthenticator.swift
Labels: SIWA
