Repository wordpress-mobile/WordPressAuthenticator-iOS, pull requests merged in 2019-12, with the labels that each got.

#164 Color updates: update text button title color and configure alternative button in `LoginEmailViewController`
  WordPressAuthenticator.podspec
  WordPressAuthenticator/Extensions/WPStyleGuide+Login.swift
  WordPressAuthenticator/Signin/Login2FAViewController.swift
  WordPressAuthenticator/Signin/LoginEmailViewController.swift
  WordPressAuthenticator/Signin/LoginLinkRequestViewController.swift
  WordPressAuthenticator/Signin/LoginSelfHostedViewController.swift
  WordPressAuthenticator/Signin/LoginSiteAddressViewController.swift
  WordPressAuthenticator/Signin/LoginUsernamePasswordViewController.swift
  WordPressAuthenticator/Signin/LoginWPComViewController.swift
Labels: Dark mode

#165 Color update: style the send code button in `viewWillAppear` in `Login2FAViewController`
  WordPressAuthenticator.podspec
  WordPressAuthenticator/Signin/Login2FAViewController.swift
Labels: Dark mode

#166 [VoiceOver] Login and Signup enhancements
  WordPressAuthenticator.podspec
  WordPressAuthenticator/Signin/Login.storyboard
  WordPressAuthenticator/Signin/LoginPrologueLoginMethodViewController.swift
  WordPressAuthenticator/Signin/LoginPrologueSignupMethodViewController.swift
Labels: enhancement

#169 Upgrade Xcode to 11.2.1 in CI
  .circleci/config.yml
Labels: enhancement

#170 [VoiceOver] Self-hosted Login Flow enhancements
  WordPressAuthenticator.podspec
  WordPressAuthenticator/Authenticator/WordPressAuthenticatorDisplayStrings.swift
  WordPressAuthenticator/Extensions/WPStyleGuide+Login.swift
  WordPressAuthenticator/NUX/WPWalkthroughTextField.m
  WordPressAuthenticator/Signin/LoginSelfHostedViewController.swift
  WordPressAuthenticator/Signin/LoginSiteAddressViewController.swift
  WordPressAuthenticator/Signin/LoginViewController.swift
Labels: VoiceOver, enhancement
