Repository wordpress-mobile/WordPressAuthenticator-iOS, pull requests merged in 2020-09, with the labels that each got.

#430 UL&S: Update the prologue buttons
  WordPressAuthenticator.podspec
  WordPressAuthenticator/Signin/LoginPrologueViewController.swift
Labels: enhancement

#431 ULS Get Started: add "OR" divider view
  WordPressAuthenticator.podspec
  WordPressAuthenticator/Extensions/WPStyleGuide+Login.swift
  WordPressAuthenticator/Unified Auth/View Related/Get Started/GetStarted.storyboard
  WordPressAuthenticator/Unified Auth/View Related/Get Started/GetStartedViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/Reusable Views/TextFieldTableViewCell.swift
  WordPressAuthenticator/Unified Auth/View Related/Reusable Views/TextLinkButtonTableViewCell.swift
Labels: enhancement

#433 ULS Get Started: add Social login options
  WordPressAuthenticator.podspec
  WordPressAuthenticator/Authenticator/WordPressAuthenticatorDisplayStrings.swift
  WordPressAuthenticator/Extensions/WPStyleGuide+Login.swift
  WordPressAuthenticator/NUX/NUXButtonViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/Get Started/GetStarted.storyboard
  WordPressAuthenticator/Unified Auth/View Related/Get Started/GetStartedViewController.swift
Labels: enhancement

#435 ULS Get Started: add email address handling
  Podfile
  Podfile.lock
  WordPressAuthenticator.podspec
  WordPressAuthenticator/Authenticator/WordPressAuthenticatorDisplayStrings.swift
  WordPressAuthenticator/Signin/LoginViewController.swift
  WordPressAuthenticator/Unified Auth/StoredCredentialsAuthenticator.swift
  WordPressAuthenticator/Unified Auth/View Related/2FA/TwoFAViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/Get Started/GetStartedViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/Password/PasswordViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/Reusable Views/TextFieldTableViewCell.swift
  WordPressAuthenticator/Unified Auth/View Related/Sign up/UnifiedSignupViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/Site Address/SiteAddressViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/Site Address/SiteCredentialsViewController.swift
Labels: enhancement

#434 UL&S Tracking: fix several tracking issues
  WordPressAuthenticator.podspec
  WordPressAuthenticator/Analytics/AuthenticatorAnalyticsTracker.swift
  WordPressAuthenticator/Extensions/FancyAlertViewController+LoginError.swift
  WordPressAuthenticator/Signin/LoginPrologueViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/2FA/TwoFAViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/Password/PasswordViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/Site Address/SiteAddressViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/Site Address/SiteCredentialsViewController.swift
  WordPressAuthenticatorTests/Analytics/AnalyticsTrackerTests.swift
Labels: bug

#438 ULS Get Started: add password manager support
  WordPressAuthenticator.podspec
  WordPressAuthenticator/Unified Auth/View Related/Get Started/GetStarted.storyboard
  WordPressAuthenticator/Unified Auth/View Related/Get Started/GetStartedViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/Reusable Views/TextFieldTableViewCell.swift
  WordPressAuthenticator/Unified Auth/View Related/Site Address/SiteCredentialsViewController.swift
Labels: enhancement

#442 Merge release/1.24 back into develop
  WordPressAuthenticator.podspec
Labels: releases

#443 Release/1.24.0
  Podfile
  Podfile.lock
  WordPressAuthenticator.podspec
  WordPressAuthenticator.xcodeproj/project.pbxproj
  WordPressAuthenticator.xcodeproj/xcshareddata/xcschemes/WordPressAuthenticator.xcscheme
  WordPressAuthenticator/Analytics/AuthenticatorAnalyticsTracker.swift
  WordPressAuthenticator/Authenticator/WordPressAuthenticator.swift
  WordPressAuthenticator/Authenticator/WordPressAuthenticatorConfiguration.swift
  WordPressAuthenticator/Authenticator/WordPressAuthenticatorDisplayStrings.swift
  WordPressAuthenticator/Extensions/FancyAlertViewController+LoginError.swift
  WordPressAuthenticator/Extensions/UIImage+Assets.swift
  WordPressAuthenticator/Extensions/UIStoryboard+Helpers.swift
  WordPressAuthenticator/Extensions/WPStyleGuide+Login.swift
  WordPressAuthenticator/Model/LoginFields.swift
  WordPressAuthenticator/NUX/ModalViewControllerPresenting.swift
  WordPressAuthenticator/NUX/NUXButtonViewController.swift
  WordPressAuthenticator/Resources/Assets.xcassets/apple-black.imageset/Contents.json
  WordPressAuthenticator/Resources/Assets.xcassets/apple-black.imageset/apple-black.pdf
  WordPressAuthenticator/Resources/Assets.xcassets/apple-white.imageset/Contents.json
  WordPressAuthenticator/Resources/Assets.xcassets/apple-white.imageset/apple-white.pdf
  WordPressAuthenticator/Services/OnePasswordFacade.swift
  WordPressAuthenticator/Services/OnePasswordResultsFetcher.swift
  WordPressAuthenticator/Signin/AppleAuthenticator.swift
  WordPressAuthenticator/Signin/LoginPrologueLoginMethodViewController.swift
  WordPressAuthenticator/Signin/LoginPrologueViewController.swift
  WordPressAuthenticator/Signin/LoginViewController.swift
  WordPressAuthenticator/Signin/LoginWPComViewController.swift
  WordPressAuthenticator/Unified Auth/StoredCredentialsAuthenticator.swift
  WordPressAuthenticator/Unified Auth/StoredCredentialsPicker.swift
  WordPressAuthenticator/Unified Auth/View Related/2FA/TwoFAViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/Get Started/GetStarted.storyboard
  WordPressAuthenticator/Unified Auth/View Related/Get Started/GetStartedViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/Login/LoginMagicLinkViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/Password/PasswordViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/Reusable Views/TextFieldTableViewCell.swift
  WordPressAuthenticator/Unified Auth/View Related/Reusable Views/TextLinkButtonTableViewCell.swift
  WordPressAuthenticator/Unified Auth/View Related/Reusable Views/TextLinkButtonTableViewCell.xib
  WordPressAuthenticator/Unified Auth/View Related/Reusable Views/TextWithLinkTableViewCell.swift
  WordPressAuthenticator/Unified Auth/View Related/Reusable Views/TextWithLinkTableViewCell.xib
  WordPressAuthenticator/Unified Auth/View Related/Sign up/UnifiedSignupViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/Site Address/SiteAddressViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/Site Address/SiteCredentialsViewController.swift
  WordPressAuthenticatorTests/Analytics/AnalyticsTrackerTests.swift
  WordPressAuthenticatorTests/Authenticator/WordPressAuthenticatorTests.swift
  WordPressAuthenticatorTests/Authenticator/WordPressSourceTagTests.swift
  WordPressAuthenticatorTests/Credentials/CredentialsTests.swift
  WordPressAuthenticatorTests/Mocks/MockOnePasswordFacade.swift
  WordPressAuthenticatorTests/Mocks/ModalViewControllerPresentingSpy.swift
  WordPressAuthenticatorTests/Mocks/WordpressAuthenticatorProvider.swift
Labels: releases

#444 ULS: Show unified views for Jetpack login and re-authentication
  WordPressAuthenticator/Authenticator/WordPressAuthenticator.swift
Labels: bug

#446 UL&S iCloud Keychain: attempt to fix backgrounding issue.
  WordPressAuthenticator/Signin/LoginPrologueViewController.swift
Labels: bug

#445 Open magic links to the correct screen
  WordPressAuthenticator/Unified Auth/View Related/Sign up/UnifiedSignupViewController.swift
Labels: bug

#448 ULS: add accessibility identifiers used by WPiOS UI tests
  WordPressAuthenticator/NUX/NUXViewController.swift
  WordPressAuthenticator/Signin/LoginPrologueViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/Get Started/GetStartedViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/Login/LoginMagicLinkViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/Password/PasswordViewController.swift
Labels: enhancement

#450 Merging `release/1.24.1` changes into `trunk`
  WordPressAuthenticator.podspec
  WordPressAuthenticator/Authenticator/WordPressAuthenticator.swift
  WordPressAuthenticator/NUX/NUXViewController.swift
  WordPressAuthenticator/Signin/LoginPrologueViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/Get Started/GetStartedViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/Login/LoginMagicLinkViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/Password/PasswordViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/Sign up/UnifiedSignupViewController.swift
Labels: releases

#452 Make the NUX button wordwrap so that iOS 12.4 users can read it
  WordPressAuthenticator.podspec
  WordPressAuthenticator/NUX/NUXButtonView.storyboard
Labels: bug

#454 UL&S: Implements tracking for the WPcom flow and Magic Links.
  WordPressAuthenticator.xcodeproj/project.pbxproj
  WordPressAuthenticator/Analytics/AuthenticatorAnalyticsTracker.swift
  WordPressAuthenticator/Extensions/UIViewController+Dismissal.swift
  WordPressAuthenticator/NUX/NUXLinkAuthViewController.swift
  WordPressAuthenticator/NUX/NUXViewControllerBase.swift
  WordPressAuthenticator/Signin/AppleAuthenticator.swift
  WordPressAuthenticator/Signin/LoginPrologueViewController.swift
  WordPressAuthenticator/Signin/LoginViewController.swift
  WordPressAuthenticator/Unified Auth/StoredCredentialsAuthenticator.swift
  WordPressAuthenticator/Unified Auth/View Related/Get Started/GetStartedViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/Login/LoginMagicLinkViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/Password/PasswordViewController.swift
Labels: enhancement

#457 ULS: Size Prologue button width based on view.
  WordPressAuthenticator.podspec
  WordPressAuthenticator/Signin/Login.storyboard
  WordPressAuthenticator/Signin/LoginPrologueViewController.swift
Labels: enhancement

#461 ULS Site Address: Redirect to WP login if site is hosted on WP.
  WordPressAuthenticator/Unified Auth/View Related/Site Address/SiteAddressViewController.swift
Labels: enhancement

#462 UL&S: Adds tracking for WPCom signups.
  WordPressAuthenticator/Analytics/AuthenticatorAnalyticsTracker.swift
  WordPressAuthenticator/Unified Auth/View Related/Get Started/GetStartedViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/Sign up/SignupMagicLinkViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/Sign up/UnifiedSignupViewController.swift
Labels: enhancement

#463 Login: show correct message when login limit reached
  WordPressAuthenticator.podspec
  WordPressAuthenticator/Unified Auth/View Related/Password/PasswordViewController.swift
Labels: bug

#465 Release 1.24.4
  WordPressAuthenticator.podspec
  WordPressAuthenticator/Analytics/AuthenticatorAnalyticsTracker.swift
  WordPressAuthenticator/Unified Auth/View Related/Get Started/GetStartedViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/Reusable Views/TextLinkButtonTableViewCell.xib
  WordPressAuthenticator/Unified Auth/View Related/Sign up/SignupMagicLinkViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/Sign up/UnifiedSignupViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/Site Address/SiteAddressViewController.swift
Labels: releases

#467 Trunk to develop
  WordPressAuthenticator.podspec
  WordPressAuthenticator/Analytics/AuthenticatorAnalyticsTracker.swift
  WordPressAuthenticator/Unified Auth/View Related/Get Started/GetStartedViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/Reusable Views/TextLinkButtonTableViewCell.xib
  WordPressAuthenticator/Unified Auth/View Related/Sign up/SignupMagicLinkViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/Sign up/UnifiedSignupViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/Site Address/SiteAddressViewController.swift
Labels: releases

#468 UL&S Tracking: fix tracking issues in the WPcom and Magic link flows.
  WordPressAuthenticator/Analytics/AuthenticatorAnalyticsTracker.swift
  WordPressAuthenticator/Unified Auth/View Related/Get Started/GetStartedViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/Login/LoginMagicLinkViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/Password/PasswordViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/Sign up/UnifiedSignupViewController.swift
Labels: bug

#470 UL&S: Adds tracking to the prologue, and fixes some other tracking issues.
  WordPressAuthenticator/Analytics/AuthenticatorAnalyticsTracker.swift
  WordPressAuthenticator/Extensions/UIViewController+Dismissal.swift
  WordPressAuthenticator/Signin/AppleAuthenticator.swift
  WordPressAuthenticator/Signin/LoginPrologueViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/Get Started/GetStartedViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/Login/LoginMagicLinkViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/Password/PasswordViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/Sign up/UnifiedSignupViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/Site Address/SiteAddressViewController.swift
Labels: enhancement

#471 UL&S fixes some tracking issues.
  WordPressAuthenticator/Analytics/AuthenticatorAnalyticsTracker.swift
  WordPressAuthenticator/Unified Auth/GoogleAuthenticator.swift
  WordPressAuthenticator/Unified Auth/View Related/Google/GoogleSignupConfirmationViewController.swift
Labels: bug

#474 Release 1.25.0
  WordPressAuthenticator.podspec
  WordPressAuthenticator/Signin/Login.storyboard
  WordPressAuthenticator/Signin/LoginPrologueViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/Password/PasswordViewController.swift
Labels: releases

#476 ULS: Remove enableUnifiedSiteAddress flag.
  WordPressAuthenticator.podspec
  WordPressAuthenticator/Analytics/AuthenticatorAnalyticsTracker.swift
  WordPressAuthenticator/Authenticator/WordPressAuthenticator.swift
  WordPressAuthenticator/Authenticator/WordPressAuthenticatorConfiguration.swift
  WordPressAuthenticator/Signin/LoginPrologueViewController.swift
  WordPressAuthenticator/Signin/LoginViewController.swift
Labels: enhancement

#477 ULS: Remove enableUnifiedGoogle flag.
  WordPressAuthenticator.podspec
  WordPressAuthenticator/Analytics/AuthenticatorAnalyticsTracker.swift
  WordPressAuthenticator/Authenticator/WordPressAuthenticatorConfiguration.swift
  WordPressAuthenticator/Signin/LoginEmailViewController.swift
  WordPressAuthenticator/Signin/LoginPrologueViewController.swift
  WordPressAuthenticator/Signin/LoginSocialErrorViewController.swift
  WordPressAuthenticator/Signin/LoginViewController.swift
  WordPressAuthenticator/Unified Auth/GoogleAuthenticator.swift
Labels: enhancement

#478 ULS: Remove enableUnifiedApple flag.
  WordPressAuthenticator.podspec
  WordPressAuthenticator/Analytics/AuthenticatorAnalyticsTracker.swift
  WordPressAuthenticator/Authenticator/WordPressAuthenticatorConfiguration.swift
  WordPressAuthenticator/Signin/LoginPrologueViewController.swift
  WordPressAuthenticator/Signin/LoginSocialErrorViewController.swift
  WordPressAuthenticator/Signin/LoginViewController.swift
Labels: enhancement

#479 ULS: Remove enableUnifiedKeychainLogin flag.
  WordPressAuthenticator.podspec
  WordPressAuthenticator/Analytics/AuthenticatorAnalyticsTracker.swift
  WordPressAuthenticator/Authenticator/WordPressAuthenticatorConfiguration.swift
  WordPressAuthenticator/Signin/LoginPrologueViewController.swift
Labels: enhancement

#480 ULS: Remove enableUnifiedWordPress flag.
  WordPressAuthenticator.podspec
  WordPressAuthenticator/Analytics/AuthenticatorAnalyticsTracker.swift
  WordPressAuthenticator/Authenticator/WordPressAuthenticator.swift
  WordPressAuthenticator/Authenticator/WordPressAuthenticatorConfiguration.swift
  WordPressAuthenticator/Signin/LoginPrologueViewController.swift
  WordPressAuthenticator/Signin/LoginViewController.swift
  WordPressAuthenticator/Unified Auth/StoredCredentialsAuthenticator.swift
Labels: enhancement

#481 Password view: Disable login link button after tapped.
  WordPressAuthenticator.podspec
  WordPressAuthenticator/Unified Auth/View Related/Password/PasswordViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/Reusable Views/TextLinkButtonTableViewCell.swift
Labels: bug

#483 Fixes tracking for the iCloud Keychain flow.
  WordPressAuthenticator.podspec
  WordPressAuthenticator/Unified Auth/StoredCredentialsAuthenticator.swift
Labels: bug

#484 iCloud Keychain: Show HUD after account is selected.
  WordPressAuthenticator.podspec
  WordPressAuthenticator/Unified Auth/StoredCredentialsAuthenticator.swift
Labels: enhancement

#486 UL&S Adds self_hosted source.
  WordPressAuthenticator.podspec
  WordPressAuthenticator/Analytics/AuthenticatorAnalyticsTracker.swift
  WordPressAuthenticator/Authenticator/WordPressAuthenticator.swift
Labels: enhancement

#485 Unified Google: don't track unknown user error
  WordPressAuthenticator.podspec
  WordPressAuthenticator/Unified Auth/GoogleAuthenticator.swift
Labels: enhancement

#487 ULS: Add visual blur to Prologue button view
  WordPressAuthenticator.podspec
  WordPressAuthenticator/Signin/Login.storyboard
  WordPressAuthenticator/Signin/LoginPrologueViewController.swift
Labels: enhancement
