Repository wordpress-mobile/WordPressAuthenticator-iOS, pull requests merged in 2020-10, with the labels that each got.

#490 ULS Prologue button view: fix visual blur for iPad
  WordPressAuthenticator.podspec
  WordPressAuthenticator/Signin/Login.storyboard
Labels: enhancement

#489 UL&S: Implements re-authentication flow tracking
  WordPressAuthenticator.podspec
  WordPressAuthenticator.xcodeproj/project.pbxproj
  WordPressAuthenticator/Analytics/AuthenticatorAnalyticsTracker.swift
  WordPressAuthenticator/Authenticator/WordPressAuthenticator.swift
  WordPressAuthenticatorTests/Analytics/AnalyticsTrackerTests.swift
  WordPressAuthenticatorTests/Mocks/WordpressAuthenticatorProvider.swift
  WordPressAuthenticatorTests/Services/LoginFacadeTests.m
  WordPressAuthenticatorTests/SupportingFiles/WordPressAuthenticatorTests-Bridging-Header.h
Labels: enhancement

#491 Merge release/1.26.0 back into develop
  Podfile
  Podfile.lock
  WordPressAuthenticator.podspec
Labels: releases

#492 Release/1.26.0
  Podfile
  Podfile.lock
  WordPressAuthenticator.podspec
  WordPressAuthenticator.xcodeproj/project.pbxproj
  WordPressAuthenticator/Analytics/AuthenticatorAnalyticsTracker.swift
  WordPressAuthenticator/Authenticator/WordPressAuthenticator.swift
  WordPressAuthenticator/Authenticator/WordPressAuthenticatorConfiguration.swift
  WordPressAuthenticator/Signin/Login.storyboard
  WordPressAuthenticator/Signin/LoginEmailViewController.swift
  WordPressAuthenticator/Signin/LoginPrologueViewController.swift
  WordPressAuthenticator/Signin/LoginSocialErrorViewController.swift
  WordPressAuthenticator/Signin/LoginViewController.swift
  WordPressAuthenticator/Unified Auth/GoogleAuthenticator.swift
  WordPressAuthenticator/Unified Auth/StoredCredentialsAuthenticator.swift
  WordPressAuthenticator/Unified Auth/View Related/Password/PasswordViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/Reusable Views/TextLinkButtonTableViewCell.swift
  WordPressAuthenticatorTests/Analytics/AnalyticsTrackerTests.swift
  WordPressAuthenticatorTests/Mocks/WordpressAuthenticatorProvider.swift
  WordPressAuthenticatorTests/Services/LoginFacadeTests.m
  WordPressAuthenticatorTests/SupportingFiles/WordPressAuthenticatorTests-Bridging-Header.h
Labels: releases

#493 Remove localization from accessibility IDs
  WordPressAuthenticator.podspec
  WordPressAuthenticator/Unified Auth/View Related/Reusable Views/TextFieldTableViewCell.swift
Labels: bug

#496 Update the project and scheme to Xcode 12 recommended settings
  WordPressAuthenticator.podspec
  WordPressAuthenticator.xcodeproj/project.pbxproj
  WordPressAuthenticator.xcodeproj/xcshareddata/xcschemes/WordPressAuthenticator.xcscheme
Labels: enhancement

#497 Prologue Carousel: add a feature flag
  WordPressAuthenticator.podspec
  WordPressAuthenticator/Authenticator/WordPressAuthenticatorConfiguration.swift
Labels: enhancement

#498 Prologue Carousel: update headlines
  WordPressAuthenticator.podspec
  WordPressAuthenticator/Signin/LoginProloguePageViewController.swift
  WordPressAuthenticator/Signin/LoginProloguePromoViewController.swift
Labels: enhancement

#505 Merge 1.27.0 into trunk
  WordPressAuthenticator.podspec
  WordPressAuthenticator.xcodeproj/project.pbxproj
  WordPressAuthenticator.xcodeproj/xcshareddata/xcschemes/WordPressAuthenticator.xcscheme
  WordPressAuthenticator/Authenticator/WordPressAuthenticatorConfiguration.swift
  WordPressAuthenticator/Signin/LoginProloguePageViewController.swift
  WordPressAuthenticator/Signin/LoginProloguePromoViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/Reusable Views/TextFieldTableViewCell.swift
Labels: releases

#506 Removes a green background color from a stack view.
  WordPressAuthenticator.podspec
  WordPressAuthenticator/Signin/Login.storyboard
Labels: bug

#507 Issues/configure instruction text
  WordPressAuthenticator.podspec
  WordPressAuthenticator/Authenticator/WordPressAuthenticatorDisplayStrings.swift
  WordPressAuthenticator/Signin/Login.storyboard
  WordPressAuthenticator/Signin/LoginUsernamePasswordViewController.swift
Labels: enhancement
