Repository wordpress-mobile/WordPressAuthenticator-iOS, pull requests merged in 2020-12, with the labels that each got.

#527 Assign Help button in custom UI injected by host apps
  WordPressAuthenticator/Unified Auth/View Related/Site Address/SiteAddressViewController.swift
Labels: enhancement

#524 Add a command to pop to the root of the login flow
  WordPressAuthenticator.xcodeproj/project.pbxproj
  WordPressAuthenticator/Navigation/NavigateToRoot.swift
  WordPressAuthenticatorTests/Navigation/NavigationToRootTests.swift
Labels: enhancement

#532 Add a command to navigate back one step
  WordPressAuthenticator.podspec
  WordPressAuthenticator.xcodeproj/project.pbxproj
  WordPressAuthenticator/Navigation/NavigateBack.swift
  WordPressAuthenticatorTests/Navigation/NavigateBackTests.swift
Labels: enhancement

#525 Add new methods to WPAuthenticatorDelegate to allow host apps to handle errors
  WordPressAuthenticator.podspec
  WordPressAuthenticator/Authenticator/WordPressAuthenticatorDelegateProtocol.swift
  WordPressAuthenticator/Signin/LoginViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/Site Address/SiteAddressViewController.swift
Labels: enhancement

#534 Allow host apps to insert custom UI instead of WP.com account creation flow
  WordPressAuthenticator.podspec
  WordPressAuthenticator/Unified Auth/View Related/Get Started/GetStartedViewController.swift
Labels: enhancement

#536 Allow host apps to remove the link to the WP.com Terms Of Service
  WordPressAuthenticator.podspec
  WordPressAuthenticator/Authenticator/WordPressAuthenticatorDelegateProtocol.swift
  WordPressAuthenticator/Unified Auth/View Related/Get Started/GetStartedViewController.swift
Labels: enhancement

#539 Allow host apps to customize the background of the login prologue
  WordPressAuthenticator/Authenticator/WordPressAuthenticatorStyles.swift
  WordPressAuthenticator/Signin/LoginPrologueViewController.swift
Labels: enhancement

#529 Adjust the WordPressUI Dependency definition
  WordPressAuthenticator.podspec
Labels: releases

#537 Reduces the number of Pasteboard alerts displayed by the 2FA screen
  .circleci/config.yml
  .ruby-version
  Gemfile
  Gemfile.lock
  Podfile
  Podfile.lock
  WordPressAuthenticator.podspec
  WordPressAuthenticator.xcodeproj/project.pbxproj
  WordPressAuthenticator/Extensions/UIPasteboard+Detect.swift
  WordPressAuthenticator/Signin/Login2FAViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/2FA/TwoFAViewController.swift
Labels: enhancement

#541 Update prologue site address button title
  WordPressAuthenticator.podspec
  WordPressAuthenticator/Authenticator/WordPressAuthenticatorConfiguration.swift
  WordPressAuthenticator/Authenticator/WordPressAuthenticatorDisplayStrings.swift
  WordPressAuthenticator/Signin/LoginPrologueViewController.swift
Labels: [Pri] High, enhancement

#546 Cut 1.31.0
  .circleci/config.yml
  .ruby-version
  Gemfile
  Gemfile.lock
  Podfile
  Podfile.lock
  WordPressAuthenticator.podspec
  WordPressAuthenticator.xcodeproj/project.pbxproj
  WordPressAuthenticator/Authenticator/WordPressAuthenticatorConfiguration.swift
  WordPressAuthenticator/Authenticator/WordPressAuthenticatorDelegateProtocol.swift
  WordPressAuthenticator/Authenticator/WordPressAuthenticatorDisplayStrings.swift
  WordPressAuthenticator/Authenticator/WordPressAuthenticatorStyles.swift
  WordPressAuthenticator/Extensions/UIPasteboard+Detect.swift
  WordPressAuthenticator/Navigation/NavigateBack.swift
  WordPressAuthenticator/Navigation/NavigateToRoot.swift
  WordPressAuthenticator/Signin/Login2FAViewController.swift
  WordPressAuthenticator/Signin/LoginPrologueViewController.swift
  WordPressAuthenticator/Signin/LoginViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/2FA/TwoFAViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/Get Started/GetStartedViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/Site Address/SiteAddressViewController.swift
  WordPressAuthenticatorTests/Navigation/NavigateBackTests.swift
  WordPressAuthenticatorTests/Navigation/NavigationToRootTests.swift
Labels: releases

#544 Display a spacer cell instead of TOS when host apps remove the link to WP.com terms of service.
  WordPressAuthenticator.podspec
  WordPressAuthenticator.xcodeproj/project.pbxproj
  WordPressAuthenticator/Unified Auth/View Related/Get Started/GetStartedViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/Reusable Views/SpacerTableViewCell.swift
  WordPressAuthenticator/Unified Auth/View Related/Reusable Views/SpacerTableViewCell.xib
  WordPressAuthenticator/Unified Auth/View Related/Reusable Views/TextWithLinkTableViewCell.swift
Labels: enhancement

#549 Release 1.32.0 in trunk
  Gemfile.lock
  WordPressAuthenticator.podspec
  WordPressAuthenticator.xcodeproj/project.pbxproj
  WordPressAuthenticator/Unified Auth/View Related/Get Started/GetStartedViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/Reusable Views/SpacerTableViewCell.swift
  WordPressAuthenticator/Unified Auth/View Related/Reusable Views/SpacerTableViewCell.xib
  WordPressAuthenticator/Unified Auth/View Related/Reusable Views/TextWithLinkTableViewCell.swift
Labels: releases

#548 Release 1.32.0 in develop
  Gemfile.lock
  WordPressAuthenticator.podspec
Labels: releases

#550 Improves Jetpack Connect through Magic Links.
  Podfile.lock
  WordPressAuthenticator.podspec
  WordPressAuthenticator.xcodeproj/project.pbxproj
  WordPressAuthenticator/Authenticator/WordPressAuthenticator.swift
  WordPressAuthenticator/Extensions/URL+JetpackConnect.swift
  WordPressAuthenticator/Model/LoginFields.swift
  WordPressAuthenticator/Services/WordPressComAccountService.swift
  WordPressAuthenticator/Signin/LoginLinkRequestViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/Get Started/GetStartedViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/Password/PasswordViewController.swift
  WordPressAuthenticatorTests/Authenticator/WordPressAuthenticatorTests.swift
Labels: bug

#552 Removes the calls to update SafariCredentials.
  WordPressAuthenticator.podspec
  WordPressAuthenticator/NUX/NUXLinkAuthViewController.swift
  WordPressAuthenticator/Signin/LoginSelfHostedViewController.swift
  WordPressAuthenticator/Signin/LoginUsernamePasswordViewController.swift
  WordPressAuthenticator/Signin/LoginViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/Site Address/SiteCredentialsViewController.swift
Labels: enhancement
