Repository wordpress-mobile/WordPressAuthenticator-iOS, pull requests merged in 2020-03, with the labels that each got.

#192 Fix error handling for email verification.
  Podfile
  Podfile.lock
  WordPressAuthenticator.podspec
  WordPressAuthenticator/Signup/SignupEmailViewController.swift
Labels: bug

#196 Update WordPressKit pod to v4.6.0 beta.1
  Podfile
  Podfile.lock
  WordPressAuthenticator.podspec
Labels: enhancement

#197 Update to version 1.11.0-beta.2
  Podfile
  Podfile.lock
  WordPressAuthenticator.podspec
Labels: enhancement

#198 Integrate WPKit 4.6.0-beta.2 into the Authenticator.
  Podfile
  Podfile.lock
  WordPressAuthenticator.podspec
Labels: enhancement

#199 Update NUX buttons when light/dark mode toggled.
  WordPressAuthenticator.podspec
  WordPressAuthenticator/NUX/NUXButton.swift
Labels: Dark mode

#200 Update version of NSURL+IDN to 0.4
  Podfile
  Podfile.lock
  WordPressAuthenticator.podspec
  WordPressAuthenticator.xcodeproj/xcshareddata/xcschemes/WordPressAuthenticator.xcscheme
Labels: enhancement

#201 Update version of WordPressKit to 4.6.0-beta.6
  Podfile
  Podfile.lock
  WordPressAuthenticator.podspec
Labels: enhancement

#202 Update WP signup button style.
  WordPressAuthenticator.podspec
  WordPressAuthenticator/Extensions/WPStyleGuide+Login.swift
Labels: enhancement

#203 Update pods
  Podfile.lock
  WordPressAuthenticator.podspec
  WordPressAuthenticator/Signin/Login.storyboard
Labels: enhancement

#204 Update Lottie
  Podfile
  Podfile.lock
  WordPressAuthenticator.podspec
  WordPressAuthenticator/Signin/Login.storyboard
  WordPressAuthenticator/Signin/LoginProloguePromoViewController.swift
Labels: enhancement

#206 Updating magic link instruction text.
  WordPressAuthenticator.podspec
  WordPressAuthenticator/NUX/NUXLinkMailViewController.swift
Labels: enhancement

#208 Fixed a SignUp regression.
  Podfile
  Podfile.lock
  WordPressAuthenticator.podspec
  WordPressAuthenticator/Signup/SignupEmailViewController.swift
Labels: bug

#209 Update Google button appearance
  WordPressAuthenticator.podspec
  WordPressAuthenticator/Extensions/WPStyleGuide+Login.swift
  WordPressAuthenticator/NUX/NUXButtonViewController.swift
  WordPressAuthenticator/Signin/LoginPrologueLoginMethodViewController.swift
  WordPressAuthenticator/Signin/LoginPrologueSignupMethodViewController.swift
Labels: enhancement

#210 Updated 1PasswordExtension to a version that removes the support for UIWebView
  Podfile
  Podfile.lock
  WordPressAuthenticator.podspec
  WordPressAuthenticator/Services/OnePasswordFacade.swift
Labels: enhancement

#212 Update to Gridicons 1.0
  Podfile
  Podfile.lock
  WordPressAuthenticator.podspec
  WordPressAuthenticator/Extensions/WPStyleGuide+Login.swift
  WordPressAuthenticator/NUX/WPWalkthroughTextField.m
  WordPressAuthenticator/Signin/LoginSocialErrorViewController.swift
Labels: enhancement

#207 Remove segue .showLoginEmail
  Podfile
  Podfile.lock
  WordPressAuthenticator.podspec
  WordPressAuthenticator.xcodeproj/project.pbxproj
  WordPressAuthenticator/Authenticator/WordPressAuthenticator.swift
  WordPressAuthenticator/Extensions/NSObject+Helpers.swift
  WordPressAuthenticator/Extensions/UIStoryboard+Helpers.swift
  WordPressAuthenticator/Extensions/UIViewController+Helpers.swift
  WordPressAuthenticator/NUX/NUXViewController.swift
  WordPressAuthenticator/Signin/Login.storyboard
  WordPressAuthenticator/Signin/LoginPrologueViewController.swift
  WordPressAuthenticator/Signin/LoginViewController.swift
  WordPressAuthenticator/Signup/Signup.storyboard
  WordPressAuthenticator/Signup/SignupEmailViewController.swift
Labels: enhancement

#215 Release/1.11.0
  Podfile
  Podfile.lock
  WordPressAuthenticator.podspec
  WordPressAuthenticator.xcodeproj/project.pbxproj
  WordPressAuthenticator.xcodeproj/xcshareddata/xcschemes/WordPressAuthenticator.xcscheme
  WordPressAuthenticator/Authenticator/WordPressAuthenticator.swift
  WordPressAuthenticator/Authenticator/WordPressAuthenticatorStyles.swift
  WordPressAuthenticator/Extensions/NSObject+Helpers.swift
  WordPressAuthenticator/Extensions/UIImage+Assets.swift
  WordPressAuthenticator/Extensions/UIStoryboard+Helpers.swift
  WordPressAuthenticator/Extensions/UIViewController+Helpers.swift
  WordPressAuthenticator/Extensions/WPStyleGuide+Login.swift
  WordPressAuthenticator/NUX/NUXButton.swift
  WordPressAuthenticator/NUX/NUXButtonView.storyboard
  WordPressAuthenticator/NUX/NUXButtonViewController.swift
  WordPressAuthenticator/NUX/NUXLinkMailViewController.swift
  WordPressAuthenticator/NUX/NUXViewController.swift
  WordPressAuthenticator/NUX/WPWalkthroughTextField.m
  WordPressAuthenticator/Resources/Assets.xcassets/apple-black.imageset/Contents.json
  WordPressAuthenticator/Resources/Assets.xcassets/apple-black.imageset/apple-black.pdf
  WordPressAuthenticator/Resources/Assets.xcassets/apple-white.imageset/Contents.json
  WordPressAuthenticator/Resources/Assets.xcassets/apple-white.imageset/apple-white.pdf
  WordPressAuthenticator/Services/OnePasswordFacade.swift
  WordPressAuthenticator/Signin/Login.storyboard
  WordPressAuthenticator/Signin/LoginPrologueLoginMethodViewController.swift
  WordPressAuthenticator/Signin/LoginProloguePromoViewController.swift
  WordPressAuthenticator/Signin/LoginPrologueSignupMethodViewController.swift
  WordPressAuthenticator/Signin/LoginPrologueViewController.swift
  WordPressAuthenticator/Signin/LoginSocialErrorViewController.swift
  WordPressAuthenticator/Signin/LoginViewController.swift
  WordPressAuthenticator/Signup/Signup.storyboard
  WordPressAuthenticator/Signup/SignupEmailViewController.swift
Labels: releases

#216 NUX button hotfix
  WordPressAuthenticator.podspec
  WordPressAuthenticator/NUX/NUXButton.swift
Labels: bug

#221 Bump the podspec to use the correct versioning
  Podfile
  Podfile.lock
  WordPressAuthenticator.podspec
Labels: bug

#222 Update WordpressKit dependency to 1.7.0-beta.1
  WordPressAuthenticator.podspec
Labels: releases

#223 Remove whitespace from translation string
  WordPressAuthenticator.podspec
  WordPressAuthenticator/Extensions/WPStyleGuide+Login.swift
  WordPressAuthenticator/NUX/NUXButton.swift
Labels: bug

#226 Merge `master` into `develop`
  WordPressAuthenticator.podspec
  WordPressAuthenticator/Extensions/WPStyleGuide+Login.swift
  WordPressAuthenticator/NUX/NUXButton.swift
Labels: bug

#219 Remove segue `.showGoogle`
  WordPressAuthenticator.podspec
  WordPressAuthenticator/NUX/NUXViewController.swift
  WordPressAuthenticator/Signin/Login.storyboard
  WordPressAuthenticator/Signin/LoginEmailViewController.swift
  WordPressAuthenticator/Signin/LoginPrologueViewController.swift
  WordPressAuthenticator/Signin/LoginSiteAddressViewController.swift
  WordPressAuthenticator/Signup/Signup.storyboard
Labels: enhancement
