Repository wordpress-mobile/WordPressAuthenticator-iOS, pull requests merged in 2020-04, with the labels that each got.

#225 UL&S: Remove `.showSignupMethod`
  WordPressAuthenticator.podspec
  WordPressAuthenticator/NUX/NUXViewController.swift
  WordPressAuthenticator/Signin/Login.storyboard
  WordPressAuthenticator/Signin/LoginEmailViewController.swift
  WordPressAuthenticator/Signin/LoginPrologueViewController.swift
Labels: enhancement

#228 UL&S: Remove `.show2FA`
  WordPressAuthenticator.podspec
  WordPressAuthenticator/NUX/NUXViewController.swift
  WordPressAuthenticator/Signin/Login.storyboard
  WordPressAuthenticator/Signin/LoginViewController.swift
Labels: enhancement

#231 Release/1.12
  Podfile
  Podfile.lock
  WordPressAuthenticator.podspec
  WordPressAuthenticator/Authenticator/WordPressAuthenticator.swift
  WordPressAuthenticator/Extensions/UIStoryboard+Helpers.swift
  WordPressAuthenticator/NUX/NUXViewController.swift
  WordPressAuthenticator/Signin/EmailMagicLink.storyboard
  WordPressAuthenticator/Signin/Login.storyboard
  WordPressAuthenticator/Signin/LoginEmailViewController.swift
  WordPressAuthenticator/Signin/LoginLinkRequestViewController.swift
  WordPressAuthenticator/Signin/LoginPrologueViewController.swift
  WordPressAuthenticator/Signin/LoginSiteAddressViewController.swift
  WordPressAuthenticator/Signin/LoginViewController.swift
  WordPressAuthenticator/Signup/Signup.storyboard
  WordPressAuthenticator/Signup/SignupEmailViewController.swift
Labels: releases

#230 Merge release 1.12 into develop
  Podfile
  Podfile.lock
  WordPressAuthenticator.podspec
Labels: releases

#234 Jetpack Signup Flow pushes 3 buttons instead of present
  WordPressAuthenticator.podspec
  WordPressAuthenticator/Signin/LoginEmailViewController.swift
Labels: bug

#235 Merge `master` into `develop`
  WordPressAuthenticator.podspec
  WordPressAuthenticator/Signin/LoginEmailViewController.swift
Labels: releases

#232 UL&S: Remove `.showSigninV2`
  WordPressAuthenticator.podspec
  WordPressAuthenticator/NUX/NUXViewController.swift
  WordPressAuthenticator/Signin/Login.storyboard
  WordPressAuthenticator/Signin/LoginEmailViewController.swift
  WordPressAuthenticator/Signin/LoginPrologueViewController.swift
  WordPressAuthenticator/Signup/Signup.storyboard
Labels: enhancement

#240 UL&S: Remove `showURLUsernamePassword`
  WordPressAuthenticator.podspec
  WordPressAuthenticator/NUX/NUXViewController.swift
  WordPressAuthenticator/Signin/Login.storyboard
  WordPressAuthenticator/Signin/LoginEmailViewController.swift
  WordPressAuthenticator/Signin/LoginSiteAddressViewController.swift
Labels: enhancement

#242 UL&S: Remove .showSelfHostedLogin
  WordPressAuthenticator.podspec
  WordPressAuthenticator/Authenticator/WordPressAuthenticator.swift
  WordPressAuthenticator/NUX/NUXViewController.swift
  WordPressAuthenticator/Signin/Login.storyboard
  WordPressAuthenticator/Signin/LoginViewController.swift
Labels: enhancement

#247 Release 1.13.0
  Podfile
  Podfile.lock
  WordPressAuthenticator.podspec
  WordPressAuthenticator/Authenticator/WordPressAuthenticator.swift
  WordPressAuthenticator/NUX/NUXViewController.swift
  WordPressAuthenticator/Signin/Login.storyboard
  WordPressAuthenticator/Signin/LoginEmailViewController.swift
  WordPressAuthenticator/Signin/LoginPrologueViewController.swift
  WordPressAuthenticator/Signin/LoginSiteAddressViewController.swift
  WordPressAuthenticator/Signin/LoginViewController.swift
  WordPressAuthenticator/Signup/Signup.storyboard
Labels: releases

#245 UL&S: Remove .showWPUsernamePassword
  WordPressAuthenticator.podspec
  WordPressAuthenticator/NUX/NUXViewController.swift
  WordPressAuthenticator/Signin/Login.storyboard
  WordPressAuthenticator/Signin/LoginSiteAddressViewController.swift
Labels: enhancement

#250 Release 1.14.0
  WordPressAuthenticator.podspec
  WordPressAuthenticator/NUX/NUXViewController.swift
  WordPressAuthenticator/Signin/Login.storyboard
  WordPressAuthenticator/Signin/LoginSiteAddressViewController.swift
Labels: releases

#252 Secure text entry button: Update when value is set.
  WordPressAuthenticator.podspec
  WordPressAuthenticator/NUX/WPWalkthroughTextField.m
Labels: enhancement

#254 UL&S: Remove .showMagicLink
  WordPressAuthenticator.podspec
  WordPressAuthenticator/NUX/NUXViewController.swift
Labels: enhancement

#256 UL&S: Remove .startMagicLinkFlow segue
  Podfile
  Podfile.lock
  WordPressAuthenticator.podspec
  WordPressAuthenticator/NUX/NUXViewController.swift
  WordPressAuthenticator/Signin/Login.storyboard
  WordPressAuthenticator/Signin/LoginEmailViewController.swift
Labels: enhancement

#261 Uses WordPressUI 1.6.0-beta.1
  Podfile
  Podfile.lock
  WordPressAuthenticator.podspec
Labels: enhancement

#260 UL&S: Remove .showDomains
  WordPressAuthenticator.podspec
  WordPressAuthenticator/NUX/NUXViewController.swift
Labels: enhancement

#263 UL&S: Remove .showCreateSite segue
  WordPressAuthenticator.podspec
  WordPressAuthenticator/NUX/NUXViewController.swift
Labels: enhancement
