Repository wordpress-mobile/WordPressAuthenticator-iOS, pull requests merged in 2020-07, with the labels that each got.

#316 ULS: Use NY font for large titles
  Podfile
  Podfile.lock
  WordPressAuthenticator.podspec
  WordPressAuthenticator/Signin/LoginViewController.swift
Labels: enhancement

#317 ULS: Don't show host app icon in unified nav bar.
  WordPressAuthenticator.podspec
  WordPressAuthenticator/NUX/NUXViewControllerBase.swift
  WordPressAuthenticator/Signin/LoginSocialErrorViewController.swift
  WordPressAuthenticator/Signin/LoginViewController.swift
Labels: enhancement

#312 UL&S: Error Label for SiteAddressViewController
  WordPressAuthenticator.podspec
  WordPressAuthenticator/Authenticator/WordPressAuthenticatorStyles.swift
  WordPressAuthenticator/Unified Auth/View Related/Reusable Views/TextFieldTableViewCell.swift
  WordPressAuthenticator/Unified Auth/View Related/Reusable Views/TextLabelTableViewCell.swift
  WordPressAuthenticator/Unified Auth/View Related/SiteAddress.storyboard
  WordPressAuthenticator/Unified Auth/View Related/SiteAddressViewController.swift
Labels: enhancement

#321 UL&S: Add the Site Address folder to the project
  WordPressAuthenticator.podspec
  WordPressAuthenticator.xcodeproj/project.pbxproj
  WordPressAuthenticator/Unified Auth/View Related/Site Address/SiteAddress.storyboard
  WordPressAuthenticator/Unified Auth/View Related/Site Address/SiteAddressViewController.swift
Labels: enhancement

#323 Fix nav bar title color
  WordPressAuthenticator/Signin/LoginViewController.swift
Labels: bug

#326 ULS: Remove support for large title nav bar.
  WordPressAuthenticator.podspec
  WordPressAuthenticator/Authenticator/WordPressAuthenticatorStyles.swift
  WordPressAuthenticator/Signin/LoginViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/Site Address/SiteAddressViewController.swift
Labels: enhancement

#324 UL&S: Navigate to a blank SiteCredentialsViewController
  WordPressAuthenticator.podspec
  WordPressAuthenticator.xcodeproj/project.pbxproj
  WordPressAuthenticator/Signin/LoginSelfHostedViewController.swift
  WordPressAuthenticator/Signin/LoginUsernamePasswordViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/Site Address/SiteAddress.storyboard
  WordPressAuthenticator/Unified Auth/View Related/Site Address/SiteAddressViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/Site Address/SiteCredentialsViewController.swift
Labels: enhancement

#329 UL&S: SiteCredentialsViewController username and password fields
  WordPressAuthenticator.podspec
  WordPressAuthenticator/Authenticator/WordPressAuthenticatorDisplayStrings.swift
  WordPressAuthenticator/Unified Auth/View Related/Reusable Views/TextFieldTableViewCell.swift
  WordPressAuthenticator/Unified Auth/View Related/Reusable Views/TextFieldTableViewCell.xib
  WordPressAuthenticator/Unified Auth/View Related/Reusable Views/TextLabelTableViewCell.xib
  WordPressAuthenticator/Unified Auth/View Related/Site Address/SiteCredentialsViewController.swift
Labels: enhancement

#333 Merge SIWA fix into develop
  WordPressAuthenticator.podspec
  WordPressAuthenticator/Signin/LoginPrologueViewController.swift
  WordPressAuthenticator/Signin/LoginViewController.swift
Labels: SIWA

#332 UL&S: SiteCredentialsViewController: OnePassword function on username for iOS 12 users
  WordPressAuthenticator.podspec
  WordPressAuthenticator/Extensions/WPStyleGuide+Login.swift
  WordPressAuthenticator/Resources/Assets.xcassets/onepassword-button.imageset/Contents.json
  WordPressAuthenticator/Unified Auth/View Related/Reusable Views/TextFieldTableViewCell.swift
  WordPressAuthenticator/Unified Auth/View Related/Reusable Views/TextFieldTableViewCell.xib
  WordPressAuthenticator/Unified Auth/View Related/Reusable Views/TextLinkButtonTableViewCell.swift
  WordPressAuthenticator/Unified Auth/View Related/Site Address/SiteAddressViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/Site Address/SiteCredentialsViewController.swift
Labels: enhancement

#341 Address whitespace issues
  WordPressAuthenticator.podspec
  WordPressAuthenticator/Unified Auth/View Related/Reusable Views/TextFieldTableViewCell.swift
  WordPressAuthenticator/Unified Auth/View Related/Reusable Views/TextLinkButtonTableViewCell.swift
  WordPressAuthenticator/Unified Auth/View Related/Site Address/SiteAddressViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/Site Address/SiteCredentialsViewController.swift
Labels: enhancement

#343 UL&S: Update the password "eye" icon tint color for the old UI
  WordPressAuthenticator.podspec
  WordPressAuthenticator/NUX/WPWalkthroughTextField.m
  WordPressAuthenticator/UI/LoginTextField.swift
Labels: enhancement

#344 ULS: Add 2FA code handling
  WordPressAuthenticator.podspec
  WordPressAuthenticator/Unified Auth/View Related/2FA/TwoFA.storyboard
  WordPressAuthenticator/Unified Auth/View Related/2FA/TwoFAViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/Google/GoogleAuthViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/Site Address/SiteAddressViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/Site Address/SiteCredentialsViewController.swift
Labels: enhancement

#348 UL&S: Navigate to a blank UnifiedSignUpViewController
  WordPressAuthenticator.podspec
  WordPressAuthenticator.xcodeproj/project.pbxproj
  WordPressAuthenticator/Authenticator/WordPressAuthenticatorConfiguration.swift
  WordPressAuthenticator/Extensions/UIStoryboard+Helpers.swift
  WordPressAuthenticator/Signin/LoginPrologueViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/Sign up/UnifiedSignUp.storyboard
  WordPressAuthenticator/Unified Auth/View Related/Sign up/UnifiedSignUpViewController.swift
Labels: enhancement

#347 ULS: 2FA - request code via SMS
  WordPressAuthenticator.podspec
  WordPressAuthenticator/Unified Auth/View Related/2FA/TwoFAViewController.swift
Labels: enhancement

#350 UL&S: Gravatar + Email UITableViewCell base UI and example
  WordPressAuthenticator.podspec
  WordPressAuthenticator.xcodeproj/project.pbxproj
  WordPressAuthenticator/Authenticator/WordPressAuthenticatorDisplayStrings.swift
  WordPressAuthenticator/Authenticator/WordPressAuthenticatorStyles.swift
  WordPressAuthenticator/Unified Auth/View Related/Reusable Views/GravatarEmailTableViewCell.swift
  WordPressAuthenticator/Unified Auth/View Related/Reusable Views/GravatarEmailTableViewCell.xib
  WordPressAuthenticator/Unified Auth/View Related/Sign up/UnifiedSignUp.storyboard
  WordPressAuthenticator/Unified Auth/View Related/Sign up/UnifiedSignUpViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/Site Address/SiteAddressViewController.swift
Labels: enhancement

#351 ULS: Show unified 2FA view for Apple
  WordPressAuthenticator.podspec
  WordPressAuthenticator/Authenticator/WordPressAuthenticatorConfiguration.swift
  WordPressAuthenticator/Signin/LoginViewController.swift
Labels: enhancement
