Repository wordpress-mobile/WordPressAuthenticator-iOS, pull requests merged in 2020-06, with the labels that each got.

#292 Release/1.17
  Podfile
  Podfile.lock
  WordPressAuthenticator.podspec
  WordPressAuthenticator.xcodeproj/project.pbxproj
  WordPressAuthenticator/Authenticator/WordPressAuthenticator.swift
  WordPressAuthenticator/Authenticator/WordPressAuthenticatorConfiguration.swift
  WordPressAuthenticator/Signin/LoginEmailViewController.swift
  WordPressAuthenticator/Signin/LoginPrologueLoginMethodViewController.swift
  WordPressAuthenticator/Signin/LoginPrologueViewController.swift
  WordPressAuthenticator/Signin/LoginSiteAddressViewController.swift
  WordPressAuthenticator/Signin/LoginViewController.swift
  WordPressAuthenticator/Signup/SignupGoogleViewController.swift
  WordPressAuthenticator/Unified Auth/GoogleAuthenticator.swift
Labels: releases

#291 Merge Release/1.17 into develop
  Podfile
  Podfile.lock
  WordPressAuthenticator.podspec
Labels: releases

#293 UL&S: navigate to blank site address view controller
  WordPressAuthenticator.podspec
  WordPressAuthenticator.xcodeproj/project.pbxproj
  WordPressAuthenticator/Extensions/UIStoryboard+Helpers.swift
  WordPressAuthenticator/Signin/LoginEmailViewController.swift
  WordPressAuthenticator/Signin/LoginPrologueViewController.swift
  WordPressAuthenticator/Signin/LoginViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/SiteAddress.storyboard
  WordPressAuthenticator/Unified Auth/View Related/SiteAddressViewController.swift
Labels: enhancement

#299 UL&S: SiteAddress: anchor Continue button to keyboard
  WordPressAuthenticator.podspec
  WordPressAuthenticator/Unified Auth/View Related/SiteAddress.storyboard
  WordPressAuthenticator/Unified Auth/View Related/SiteAddressViewController.swift
Labels: [Status] Not Ready for Review, enhancement

#302 Tag 1.18.0
  Podfile
  Podfile.lock
  WordPressAuthenticator.podspec
  WordPressAuthenticator.xcodeproj/project.pbxproj
  WordPressAuthenticator/Authenticator/WordPressAuthenticator.swift
  WordPressAuthenticator/Authenticator/WordPressAuthenticatorConfiguration.swift
  WordPressAuthenticator/Authenticator/WordPressAuthenticatorDisplayStrings.swift
  WordPressAuthenticator/Authenticator/WordPressAuthenticatorStyles.swift
  WordPressAuthenticator/Authenticator/WordPressSupportSourceTag.swift
  WordPressAuthenticator/Extensions/UIStoryboard+Helpers.swift
  WordPressAuthenticator/Signin/LoginEmailViewController.swift
  WordPressAuthenticator/Signin/LoginPrologueViewController.swift
  WordPressAuthenticator/Signin/LoginViewController.swift
  WordPressAuthenticator/Unified Auth/GoogleAuthenticator.swift
  WordPressAuthenticator/Unified Auth/View Related/Google/GoogleAuth.storyboard
  WordPressAuthenticator/Unified Auth/View Related/Google/GoogleAuthViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/Google/GoogleSignupConfirmation.storyboard
  WordPressAuthenticator/Unified Auth/View Related/Google/GoogleSignupConfirmationViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/SiteAddress.storyboard
  WordPressAuthenticator/Unified Auth/View Related/SiteAddressViewController.swift
Labels: releases

#303 Relax internal dependency constaints in Podfile
  Podfile
  Podfile.lock
Labels: enhancement

#305 UL&S: Display an instruction label on the tableview
  Podfile.lock
  WordPressAuthenticator.podspec
  WordPressAuthenticator.xcodeproj/project.pbxproj
  WordPressAuthenticator/Extensions/UIView+AuthHelpers.swift
  WordPressAuthenticator/Unified Auth/View Related/Reusable Views/InstructionTableViewCell.swift
  WordPressAuthenticator/Unified Auth/View Related/Reusable Views/InstructionTableViewCell.xib
  WordPressAuthenticator/Unified Auth/View Related/SiteAddress.storyboard
  WordPressAuthenticator/Unified Auth/View Related/SiteAddressViewController.swift
Labels: enhancement

#306 UL&S: Add TextFieldTableViewCell to SiteAddressViewController
  WordPressAuthenticator.podspec
  WordPressAuthenticator.xcodeproj/project.pbxproj
  WordPressAuthenticator/Authenticator/WordPressAuthenticatorStyles.swift
  WordPressAuthenticator/Unified Auth/View Related/Reusable Views/InstructionTableViewCell.swift
  WordPressAuthenticator/Unified Auth/View Related/Reusable Views/TextFieldTableViewCell.swift
  WordPressAuthenticator/Unified Auth/View Related/Reusable Views/TextFieldTableViewCell.xib
  WordPressAuthenticator/Unified Auth/View Related/SiteAddressViewController.swift
Labels: enhancement

#308 UL&S: Add TextLinkTableViewCell to SiteAddressViewController
  WordPressAuthenticator.podspec
  WordPressAuthenticator.xcodeproj/project.pbxproj
  WordPressAuthenticator/Authenticator/WordPressAuthenticatorConfiguration.swift
  WordPressAuthenticator/Authenticator/WordPressAuthenticatorDisplayStrings.swift
  WordPressAuthenticator/Authenticator/WordPressAuthenticatorStyles.swift
  WordPressAuthenticator/Unified Auth/View Related/Reusable Views/InstructionTableViewCell.swift
  WordPressAuthenticator/Unified Auth/View Related/Reusable Views/TextFieldTableViewCell.swift
  WordPressAuthenticator/Unified Auth/View Related/Reusable Views/TextFieldTableViewCell.xib
  WordPressAuthenticator/Unified Auth/View Related/Reusable Views/TextLabelTableViewCell.swift
  WordPressAuthenticator/Unified Auth/View Related/Reusable Views/TextLabelTableViewCell.xib
  WordPressAuthenticator/Unified Auth/View Related/Reusable Views/TextLinkButtonTableViewCell.swift
  WordPressAuthenticator/Unified Auth/View Related/Reusable Views/TextLinkButtonTableViewCell.xib
  WordPressAuthenticator/Unified Auth/View Related/SiteAddressViewController.swift
Labels: enhancement

#310 UL&S: bug fix: make the TextLinkButtonTableViewCell button word wrap, not truncate
  WordPressAuthenticator.podspec
  WordPressAuthenticator/Unified Auth/View Related/Reusable Views/TextLinkButtonTableViewCell.swift
  WordPressAuthenticator/Unified Auth/View Related/Reusable Views/TextLinkButtonTableViewCell.xib
Labels: bug

#313 Release 1.19.0
  Podfile
  Podfile.lock
  WordPressAuthenticator.podspec
  WordPressAuthenticator.xcodeproj/project.pbxproj
  WordPressAuthenticator/Authenticator/WordPressAuthenticatorConfiguration.swift
  WordPressAuthenticator/Authenticator/WordPressAuthenticatorDisplayStrings.swift
  WordPressAuthenticator/Authenticator/WordPressAuthenticatorStyles.swift
  WordPressAuthenticator/Extensions/UIView+AuthHelpers.swift
  WordPressAuthenticator/Signin/LoginNavigationController.swift
  WordPressAuthenticator/Signin/LoginViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/Reusable Views/TextFieldTableViewCell.swift
  WordPressAuthenticator/Unified Auth/View Related/Reusable Views/TextFieldTableViewCell.xib
  WordPressAuthenticator/Unified Auth/View Related/Reusable Views/TextLabelTableViewCell.swift
  WordPressAuthenticator/Unified Auth/View Related/Reusable Views/TextLabelTableViewCell.xib
  WordPressAuthenticator/Unified Auth/View Related/Reusable Views/TextLinkButtonTableViewCell.swift
  WordPressAuthenticator/Unified Auth/View Related/Reusable Views/TextLinkButtonTableViewCell.xib
  WordPressAuthenticator/Unified Auth/View Related/SiteAddress.storyboard
  WordPressAuthenticator/Unified Auth/View Related/SiteAddressViewController.swift
Labels: releases
