Repository wordpress-mobile/WordPressAuthenticator-iOS, pull requests merged in 2020-05, with the labels that each got.

#267 Release/1.15.0
  Podfile
  Podfile.lock
  WordPressAuthenticator.podspec
  WordPressAuthenticator/NUX/NUXViewController.swift
  WordPressAuthenticator/NUX/WPWalkthroughTextField.m
  WordPressAuthenticator/Signin/Login.storyboard
  WordPressAuthenticator/Signin/LoginEmailViewController.swift
Labels: releases

#266 Merge Release/1.15.0 into develop
  Podfile
  Podfile.lock
  WordPressAuthenticator.podspec
Labels: releases

#265 UL&S: Remove .showSignupEmail segue
  WordPressAuthenticator.podspec
  WordPressAuthenticator/NUX/NUXViewController.swift
  WordPressAuthenticator/Signin/Login.storyboard
Labels: enhancement

#271 UL&S: Remove .showLoginMethod
  WordPressAuthenticator.podspec
  WordPressAuthenticator/NUX/NUXViewController.swift
  WordPressAuthenticator/Signin/Login.storyboard
  WordPressAuthenticator/Signin/LoginPrologueViewController.swift
  WordPressAuthenticator/Signin/LoginSiteAddressViewController.swift
Labels: enhancement

#273 UL&S: Remove .showWPComLogin
  WordPressAuthenticator.podspec
  WordPressAuthenticator.xcodeproj/project.pbxproj
  WordPressAuthenticator/Authenticator/WordPressAuthenticator.swift
  WordPressAuthenticator/NUX/NUXLinkMailViewController.swift
  WordPressAuthenticator/NUX/NUXSegueHandler.swift
  WordPressAuthenticator/NUX/NUXViewController.swift
  WordPressAuthenticator/Signin/EmailMagicLink.storyboard
  WordPressAuthenticator/Signin/Login.storyboard
  WordPressAuthenticator/Signin/LoginEmailViewController.swift
  WordPressAuthenticator/Signin/LoginLinkRequestViewController.swift
  WordPressAuthenticator/Signin/LoginPrologueViewController.swift
  WordPressAuthenticator/Signin/LoginSiteAddressViewController.swift
  WordPressAuthenticator/Signin/LoginViewController.swift
Labels: enhancement

#275 Release/1.16
  WordPressAuthenticator.podspec
  WordPressAuthenticator.xcodeproj/project.pbxproj
  WordPressAuthenticator/Authenticator/WordPressAuthenticator.swift
  WordPressAuthenticator/NUX/NUXLinkMailViewController.swift
  WordPressAuthenticator/NUX/NUXSegueHandler.swift
  WordPressAuthenticator/NUX/NUXViewController.swift
  WordPressAuthenticator/NUX/WPWalkthroughTextField.h
  WordPressAuthenticator/NUX/WPWalkthroughTextField.m
  WordPressAuthenticator/Signin/EmailMagicLink.storyboard
  WordPressAuthenticator/Signin/Login.storyboard
  WordPressAuthenticator/Signin/LoginEmailViewController.swift
  WordPressAuthenticator/Signin/LoginLinkRequestViewController.swift
  WordPressAuthenticator/Signin/LoginPrologueViewController.swift
  WordPressAuthenticator/Signin/LoginSiteAddressViewController.swift
  WordPressAuthenticator/Signin/LoginViewController.swift
  WordPressAuthenticator/UI/LoginTextField.swift
Labels: releases

#274 Merge release/1.16 into develop
  WordPressAuthenticator.podspec
Labels: releases

#278 Release/1.16.1 - Update to WordPressUI 1.7.0
  Podfile
  Podfile.lock
  WordPressAuthenticator.podspec
Labels: releases

#281 Updated Google SignIn library to the major release 5
  Podfile
  Podfile.lock
  WordPressAuthenticator.podspec
  WordPressAuthenticator.xcodeproj/project.pbxproj
  WordPressAuthenticator/Authenticator/WordPressAuthenticator.swift
  WordPressAuthenticator/Signin/LoginViewController.swift
  WordPressAuthenticator/Signup/SignupGoogleViewController.swift
Labels: enhancement

#280 Redact tokens
  Podfile
  Podfile.lock
  WordPressAuthenticator.podspec
Labels: bug

#285 UL&S: Add a feature flag for unified site address login
  WordPressAuthenticator.podspec
  WordPressAuthenticator/Authenticator/WordPressAuthenticatorConfiguration.swift
Labels: enhancement
