Repository wordpress-mobile/WordPressAuthenticator-iOS, pull requests merged in 2020-08, with the labels that each got.

#353 ULS: password initial view
  WordPressAuthenticator.podspec
  WordPressAuthenticator.xcodeproj/project.pbxproj
  WordPressAuthenticator/Extensions/UIStoryboard+Helpers.swift
  WordPressAuthenticator/Unified Auth/View Related/Google/GoogleAuthViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/Password/Password.storyboard
  WordPressAuthenticator/Unified Auth/View Related/Password/PasswordViewController.swift
Labels: enhancement

#356 ULS: add content to Password view
  WordPressAuthenticator.podspec
  WordPressAuthenticator/Authenticator/WordPressAuthenticatorDisplayStrings.swift
  WordPressAuthenticator/Unified Auth/View Related/2FA/TwoFAViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/Password/PasswordViewController.swift
Labels: enhancement

#355 UL&S: Sign up: send magic link
  WordPressAuthenticator.podspec
  WordPressAuthenticator/Unified Auth/View Related/Reusable Views/GravatarEmailTableViewCell.xib
  WordPressAuthenticator/Unified Auth/View Related/Sign up/UnifiedSignUpViewController.swift
Labels: enhancement

#359 ULS: Password view: display user's email and Gravatar
  WordPressAuthenticator.podspec
  WordPressAuthenticator/Unified Auth/View Related/Password/PasswordViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/Reusable Views/GravatarEmailTableViewCell.swift
  WordPressAuthenticator/Unified Auth/View Related/Reusable Views/GravatarEmailTableViewCell.xib
  WordPressAuthenticator/Unified Auth/View Related/Sign up/UnifiedSignUpViewController.swift
Labels: enhancement

#363 ULS Password view: Add password validation and forgot password link action.
  WordPressAuthenticator.podspec
  WordPressAuthenticator/Signin/LoginViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/2FA/TwoFAViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/Password/PasswordViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/Site Address/SiteCredentialsViewController.swift
Labels: enhancement

#362 Implements GoogleAuthenticationTracker
  WordPressAuthenticator.podspec
  WordPressAuthenticator.xcodeproj/project.pbxproj
  WordPressAuthenticator/Analytics/GoogleAuthenticatorTracker.swift
  WordPressAuthenticator/Unified Auth/GoogleAuthenticator.swift
Labels: enhancement

#364 Fix issues in google auth basic tracking
  WordPressAuthenticator.podspec
  WordPressAuthenticator/Analytics/AnalyticsTracker.swift
  WordPressAuthenticator/Analytics/GoogleAuthenticatorTracker.swift
  WordPressAuthenticator/Authenticator/WordPressAuthenticator.swift
  WordPressAuthenticator/Signin/LoginViewController.swift
  WordPressAuthenticator/Unified Auth/GoogleAuthenticator.swift
  WordPressAuthenticator/Unified Auth/View Related/2FA/TwoFAViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/Password/PasswordViewController.swift
  WordPressAuthenticatorTests/Analytics/AnalyticsTrackerTests.swift
Labels: bug

#361 UL&S: VoiceOver support for the Site Address flow and UnifiedSignUpViewController
  Podfile.lock
  WordPressAuthenticator.podspec
  WordPressAuthenticator/Unified Auth/View Related/2FA/TwoFA.storyboard
  WordPressAuthenticator/Unified Auth/View Related/Reusable Views/TextFieldTableViewCell.swift
  WordPressAuthenticator/Unified Auth/View Related/Reusable Views/TextFieldTableViewCell.xib
  WordPressAuthenticator/Unified Auth/View Related/Sign up/UnifiedSignUp.storyboard
  WordPressAuthenticator/Unified Auth/View Related/Sign up/UnifiedSignUpViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/Site Address/SiteAddress.storyboard
  WordPressAuthenticator/Unified Auth/View Related/Site Address/SiteAddressViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/Site Address/SiteCredentialsViewController.swift
Labels: VoiceOver, enhancement

#368 Update Auth to use latest WordPressShared pod
  Podfile.lock
  WordPressAuthenticator.podspec
Labels: enhancement

#371 Constrain nav bar, and bar button appearance changes to auth classes.
  WordPressAuthenticator/Signin/LoginViewController.swift
Labels: enhancement

#370 UL&S: Use consistent naming when referring to "Signup"
  WordPressAuthenticator.podspec
  WordPressAuthenticator.xcodeproj/project.pbxproj
  WordPressAuthenticator/Extensions/UIStoryboard+Helpers.swift
  WordPressAuthenticator/Signin/LoginPrologueViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/Sign up/UnifiedSignUp.storyboard
  WordPressAuthenticator/Unified Auth/View Related/Sign up/UnifiedSignUpViewController.swift
Labels: enhancement

#369 Add VoiceOver support to TwoFAViewController
  WordPressAuthenticator.podspec
  WordPressAuthenticator/Unified Auth/View Related/2FA/TwoFAViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/Reusable Views/TextLinkButtonTableViewCell.xib
  WordPressAuthenticator/Unified Auth/View Related/Site Address/SiteAddressViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/Site Address/SiteCredentialsViewController.swift
Labels: VoiceOver, enhancement

#372 Social account logins: Don't update username when using a password manager.
  WordPressAuthenticator.podspec
  WordPressAuthenticator/Authenticator/WordPressAuthenticator.swift
  WordPressAuthenticator/Signin/LoginWPComViewController.swift
Labels: bug

#375 ULS Password view: add password manager support
  WordPressAuthenticator.podspec
  WordPressAuthenticator/Unified Auth/View Related/Password/PasswordViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/Reusable Views/GravatarEmailTableViewCell.swift
  WordPressAuthenticator/Unified Auth/View Related/Reusable Views/GravatarEmailTableViewCell.xib
Labels: enhancement

#374 UL&S: SignupMagicLinkViewController: display the UI
  WordPressAuthenticator.podspec
  WordPressAuthenticator.xcodeproj/project.pbxproj
  WordPressAuthenticator/Authenticator/WordPressAuthenticatorDisplayStrings.swift
  WordPressAuthenticator/Signin/LoginPrologueViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/Sign up/SignupMagicLinkViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/Sign up/UnifiedSignup.storyboard
  WordPressAuthenticator/Unified Auth/View Related/Sign up/UnifiedSignupViewController.swift
Labels: enhancement

#376 ULS: Show new Password and 2FA views in SIWA path
  WordPressAuthenticator.podspec
  WordPressAuthenticator/Signin/LoginPrologueViewController.swift
  WordPressAuthenticator/Signin/LoginViewController.swift
Labels: enhancement

#377 ULS Password: add 1Password button action
  WordPressAuthenticator.podspec
  WordPressAuthenticator/Unified Auth/View Related/Password/PasswordViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/Reusable Views/GravatarEmailTableViewCell.swift
Labels: enhancement

#378 ULS Password view: Add VoiceOver support
  WordPressAuthenticator.podspec
  WordPressAuthenticator/Extensions/WPStyleGuide+Login.swift
  WordPressAuthenticator/Unified Auth/View Related/2FA/TwoFAViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/Password/PasswordViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/Reusable Views/GravatarEmailTableViewCell.xib
Labels: VoiceOver, enhancement

#382 UL&S: add Login folder to unified auth
  WordPressAuthenticator.podspec
  WordPressAuthenticator.xcodeproj/project.pbxproj
Labels: enhancement

#379 UL&S: SignupMagicLinkViewController: Open Mail
  WordPressAuthenticator.podspec
  WordPressAuthenticator/Extensions/UIStoryboard+Helpers.swift
  WordPressAuthenticator/Signin/LoginPrologueViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/Sign up/SignupMagicLinkViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/Sign up/UnifiedSignup.storyboard
  WordPressAuthenticator/Unified Auth/View Related/Sign up/UnifiedSignupViewController.swift
Labels: enhancement

#384 ULS Google: Update Signup confirmation to new UI
  WordPressAuthenticator.podspec
  WordPressAuthenticator/Authenticator/WordPressAuthenticatorDisplayStrings.swift
  WordPressAuthenticator/Unified Auth/View Related/Google/GoogleSignupConfirmation.storyboard
  WordPressAuthenticator/Unified Auth/View Related/Google/GoogleSignupConfirmationViewController.swift
Labels: enhancement

#385 ULS: Show unified 2FA view in Site Address flow.
  WordPressAuthenticator.podspec
  WordPressAuthenticator/Signin/LoginViewController.swift
Labels: enhancement

#387 ULS: Remove the Waiting for Google view from the navigation stack.
  WordPressAuthenticator.podspec
  WordPressAuthenticator/Signin/LoginViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/2FA/TwoFAViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/Google/GoogleSignupConfirmationViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/Password/PasswordViewController.swift
Labels: enhancement

#388 ULS: Update Social Error view appearance
  WordPressAuthenticator.podspec
  WordPressAuthenticator.xcodeproj/project.pbxproj
  WordPressAuthenticator/NUX/NUXCollectionViewController.swift
  WordPressAuthenticator/NUX/NUXTableViewController.swift
  WordPressAuthenticator/NUX/NUXViewController.swift
  WordPressAuthenticator/NUX/NUXViewControllerBase.swift
  WordPressAuthenticator/Signin/LoginSocialErrorCell.swift
  WordPressAuthenticator/Signin/LoginSocialErrorViewController.swift
  WordPressAuthenticator/Signin/LoginViewController.swift
Labels: enhancement

#390 ULS: Fix actions from Social Error
  WordPressAuthenticator.podspec
  WordPressAuthenticator/Signin/LoginEmailViewController.swift
  WordPressAuthenticator/Signin/LoginPrologueViewController.swift
  WordPressAuthenticator/Signin/LoginViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/Site Address/SiteAddressViewController.swift
Labels: enhancement

#393 ULS Site Address: set accessibility identifiers used by WPiOS UI tests.
  WordPressAuthenticator.podspec
  WordPressAuthenticator/Unified Auth/View Related/Reusable Views/TextFieldTableViewCell.swift
  WordPressAuthenticator/Unified Auth/View Related/Site Address/SiteAddressViewController.swift
Labels: enhancement

#394 Update SIWA error message
  WordPressAuthenticator.podspec
  WordPressAuthenticator/Authenticator/WordPressAuthenticatorDisplayStrings.swift
  WordPressAuthenticator/Signin/AppleAuthenticator.swift
Labels: SIWA

#399 Merge release/1.23 back into develop
  WordPressAuthenticator.podspec
Labels: releases

#402 ULS Site Address: return VC to host app based on config
  WordPressAuthenticator.podspec
  WordPressAuthenticator/Authenticator/WordPressAuthenticator.swift
  WordPressAuthenticator/NUX/NUXViewControllerBase.swift
  WordPressAuthenticator/Unified Auth/View Related/Site Address/SiteAddressViewController.swift
Labels: enhancement

#407 UL&S: Tracks: rename step `username_password` to `password_challenge`
  WordPressAuthenticator.podspec
  WordPressAuthenticator/Analytics/AuthenticatorAnalyticsTracker.swift
Labels: bug

#409 UL&S: Password challenge bugfix
  WordPressAuthenticator.podspec
  WordPressAuthenticator/Unified Auth/View Related/Password/PasswordViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/Reusable Views/GravatarEmailTableViewCell.swift
Labels: bug

#411 Merge `main` into `develop`
  WordPressAuthenticator.podspec
  WordPressAuthenticator/Analytics/AuthenticatorAnalyticsTracker.swift
  WordPressAuthenticator/Unified Auth/View Related/Password/PasswordViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/Reusable Views/GravatarEmailTableViewCell.swift
Labels: releases

#412 ULS: Initial Get Started view
  WordPressAuthenticator.podspec
  WordPressAuthenticator.xcodeproj/project.pbxproj
  WordPressAuthenticator/Authenticator/WordPressAuthenticatorConfiguration.swift
  WordPressAuthenticator/Authenticator/WordPressAuthenticatorDisplayStrings.swift
  WordPressAuthenticator/Extensions/UIStoryboard+Helpers.swift
  WordPressAuthenticator/Signin/LoginPrologueViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/Get Started/GetStarted.storyboard
  WordPressAuthenticator/Unified Auth/View Related/Get Started/GetStartedViewController.swift
Labels: enhancement

#413 UL&S iCloud Keychain: Basic implementation
  WordPressAuthenticator.podspec
  WordPressAuthenticator.xcodeproj/project.pbxproj
  WordPressAuthenticator/Analytics/AuthenticatorAnalyticsTracker.swift
  WordPressAuthenticator/Authenticator/WordPressAuthenticatorConfiguration.swift
  WordPressAuthenticator/Model/LoginFields.swift
  WordPressAuthenticator/Signin/LoginPrologueViewController.swift
  WordPressAuthenticator/Unified Auth/StoredCredentialsAuthenticator.swift
  WordPressAuthenticator/Unified Auth/StoredCredentialsPicker.swift
  WordPressAuthenticatorTests/Analytics/AnalyticsTrackerTests.swift
Labels: enhancement

#403 UL&S: PasswordViewController: send a magic link
  WordPressAuthenticator.podspec
  WordPressAuthenticator/Authenticator/WordPressAuthenticatorDisplayStrings.swift
  WordPressAuthenticator/Signin/LoginPrologueLoginMethodViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/Login/LoginMagicLinkViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/Password/PasswordViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/Reusable Views/TextLinkButtonTableViewCell.swift
  WordPressAuthenticator/Unified Auth/View Related/Reusable Views/TextLinkButtonTableViewCell.xib
Labels: enhancement

#414 ULS Get Started: add Terms of Service table cell
  WordPressAuthenticator.podspec
  WordPressAuthenticator.xcodeproj/project.pbxproj
  WordPressAuthenticator/Authenticator/WordPressAuthenticatorDisplayStrings.swift
  WordPressAuthenticator/Unified Auth/View Related/Get Started/GetStartedViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/Reusable Views/TextLinkButtonTableViewCell.swift
  WordPressAuthenticator/Unified Auth/View Related/Reusable Views/TextWithLinkTableViewCell.swift
  WordPressAuthenticator/Unified Auth/View Related/Reusable Views/TextWithLinkTableViewCell.xib
Labels: enhancement

#416 ULS Get Started: add Email Address field
  WordPressAuthenticator.podspec
  WordPressAuthenticator/Authenticator/WordPressAuthenticatorDisplayStrings.swift
  WordPressAuthenticator/Unified Auth/View Related/Get Started/GetStartedViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/Reusable Views/TextFieldTableViewCell.swift
Labels: enhancement

#415 UL&S iCloud Keychain: Simple successful login path
  WordPressAuthenticator.podspec
  WordPressAuthenticator/Signin/LoginPrologueViewController.swift
  WordPressAuthenticator/Signin/LoginViewController.swift
  WordPressAuthenticator/Unified Auth/StoredCredentialsAuthenticator.swift
Labels: enhancement

#419 ULS: fix unified Google issues
  WordPressAuthenticator/Signin/LoginSocialErrorViewController.swift
  WordPressAuthenticator/Signin/LoginViewController.swift
  WordPressAuthenticator/Unified Auth/GoogleAuthenticator.swift
  WordPressAuthenticator/Unified Auth/View Related/Google/GoogleAuth.storyboard
Labels: bug

#420 ULS: correct nav bar colors in iOS12
  WordPressAuthenticator/NUX/NUXViewControllerBase.swift
Labels: bug

#424 Merging `1.23.3` changes int `main`
  WordPressAuthenticator.podspec
  WordPressAuthenticator/NUX/NUXViewControllerBase.swift
  WordPressAuthenticator/Signin/LoginSocialErrorViewController.swift
  WordPressAuthenticator/Signin/LoginViewController.swift
  WordPressAuthenticator/Unified Auth/GoogleAuthenticator.swift
  WordPressAuthenticator/Unified Auth/View Related/Google/GoogleAuth.storyboard
Labels: bug

#427 Merge `main` into `develop`
  WordPressAuthenticator.podspec
  WordPressAuthenticator/Signin/LoginSocialErrorViewController.swift
  WordPressAuthenticator/Signin/LoginViewController.swift
  WordPressAuthenticator/Unified Auth/GoogleAuthenticator.swift
  WordPressAuthenticator/Unified Auth/View Related/Google/GoogleAuth.storyboard
Labels: releases

#428 ULS Get Started: add Continue button
  WordPressAuthenticator.podspec
  WordPressAuthenticator/Unified Auth/View Related/Get Started/GetStartedViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/Reusable Views/TextWithLinkTableViewCell.xib
Labels: enhancement
