Repository wordpress-mobile/WordPressAuthenticator-iOS, pull requests merged in 2021-01, with the labels that each got.

#555 Implement support for navigating to login with email address for self-hosted sites
  WordPressAuthenticator.podspec
  WordPressAuthenticator/Authenticator/WordPressAuthenticatorResult.swift
  WordPressAuthenticator/Signin/LoginSiteAddressViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/Site Address/SiteAddressViewController.swift
Labels: enhancement

#553 Fix magic link issues.
  Podfile.lock
  WordPressAuthenticator.podspec
  WordPressAuthenticator/Authenticator/WordPressAuthenticator.swift
  WordPressAuthenticator/Credentials/WordPressComCredentials.swift
  WordPressAuthenticator/NUX/NUXLinkAuthViewController.swift
  WordPressAuthenticator/Services/WordPressComAccountService.swift
  WordPressAuthenticator/Signin/LoginLinkRequestViewController.swift
  WordPressAuthenticator/Signin/LoginViewController.swift
  WordPressAuthenticator/Signup/SignupEmailViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/Get Started/GetStartedViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/Password/PasswordViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/Sign up/UnifiedSignupViewController.swift
  WordPressAuthenticatorTests/Authenticator/WordPressAuthenticatorTests.swift
Labels: bug

#560 Release 1.33.0 -> trunk
  Podfile.lock
  WordPressAuthenticator.podspec
  WordPressAuthenticator.xcodeproj/project.pbxproj
  WordPressAuthenticator/Authenticator/WordPressAuthenticator.swift
  WordPressAuthenticator/Authenticator/WordPressAuthenticatorResult.swift
  WordPressAuthenticator/Credentials/WordPressComCredentials.swift
  WordPressAuthenticator/Extensions/FancyAlertViewController+LoginError.swift
  WordPressAuthenticator/Extensions/URL+JetpackConnect.swift
  WordPressAuthenticator/Model/LoginFields.swift
  WordPressAuthenticator/NUX/NUXLinkAuthViewController.swift
  WordPressAuthenticator/Services/WordPressComAccountService.swift
  WordPressAuthenticator/Signin/LoginLinkRequestViewController.swift
  WordPressAuthenticator/Signin/LoginSelfHostedViewController.swift
  WordPressAuthenticator/Signin/LoginSiteAddressViewController.swift
  WordPressAuthenticator/Signin/LoginUsernamePasswordViewController.swift
  WordPressAuthenticator/Signin/LoginViewController.swift
  WordPressAuthenticator/Signup/SignupEmailViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/Get Started/GetStartedViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/Password/PasswordViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/Sign up/UnifiedSignupViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/Site Address/SiteAddressViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/Site Address/SiteCredentialsViewController.swift
  WordPressAuthenticatorTests/Authenticator/WordPressAuthenticatorTests.swift
Labels: releases

#559 Release 1.33.0 -> develop
  Podfile.lock
  WordPressAuthenticator.podspec
Labels: releases

#569 Release 1.34.0 -> develop
  WordPressAuthenticator.podspec
Labels: releases

#568 Release 1.34.0 -> trunk
  WordPressAuthenticator.podspec
  WordPressAuthenticator.xcodeproj/project.pbxproj
  WordPressAuthenticator/Authenticator/WordPressAuthenticator.swift
  WordPressAuthenticator/Authenticator/WordPressAuthenticatorStyles.swift
  WordPressAuthenticator/Extensions/UIPasteboard+Detect.swift
  WordPressAuthenticator/NUX/NUXButton.swift
  WordPressAuthenticator/Signin/Login2FAViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/2FA/TwoFAViewController.swift
  WordPressAuthenticatorTests/Authenticator/PasteboardTests.swift
  WordPressAuthenticatorTests/Mocks/WordpressAuthenticatorProvider.swift
Labels: releases

#571 Fix misconfiguration in SpacerTableViewCell.xib
  WordPressAuthenticator.podspec
  WordPressAuthenticator/Unified Auth/View Related/Reusable Views/SpacerTableViewCell.xib
Labels: bug
