Repository wordpress-mobile/WordPressAuthenticator-iOS, pull requests merged in 2021-02, with the labels that each got.

#572 Update login / signup buttons copy and font
  WordPressAuthenticator/Authenticator/WordPressAuthenticatorDisplayStrings.swift
  WordPressAuthenticator/Extensions/WPStyleGuide+Login.swift
  WordPressAuthenticator/NUX/NUXButton.swift
  WordPressAuthenticator/NUX/NUXButtonViewController.swift
  WordPressAuthenticator/Signin/LoginPrologueLoginMethodViewController.swift
  WordPressAuthenticator/Signin/LoginPrologueViewController.swift
Labels: enhancement

#575 Release 1.35.0 -> develop
  WordPressAuthenticator.podspec
Labels: releases

#576 Release 1.35.0 -> trunk
  WordPressAuthenticator.podspec
  WordPressAuthenticator/Authenticator/WordPressAuthenticatorDisplayStrings.swift
  WordPressAuthenticator/Extensions/WPStyleGuide+Login.swift
  WordPressAuthenticator/NUX/NUXButton.swift
  WordPressAuthenticator/NUX/NUXButtonViewController.swift
  WordPressAuthenticator/Signin/LoginPrologueLoginMethodViewController.swift
  WordPressAuthenticator/Signin/LoginPrologueViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/Reusable Views/SpacerTableViewCell.xib
Labels: releases

#574 Shorter sign up - remove Send Link by email screen
  WordPressAuthenticator.podspec
  WordPressAuthenticator/Authenticator/WordPressAuthenticatorDisplayStrings.swift
  WordPressAuthenticator/Unified Auth/View Related/Get Started/GetStartedViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/Sign up/SignupMagicLinkViewController.swift
Labels: enhancement

#577 Cut 1.35.1
  WordPressAuthenticator.podspec
  WordPressAuthenticator/Authenticator/WordPressAuthenticatorDisplayStrings.swift
  WordPressAuthenticator/Unified Auth/View Related/Get Started/GetStartedViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/Sign up/SignupMagicLinkViewController.swift
Labels: releases

#578 Stop tracking prologue step based on view presentation
  WordPressAuthenticator.podspec
  WordPressAuthenticator/Signin/LoginPrologueViewController.swift
Labels: bug
