Repository wordpress-mobile/WordPressAuthenticator-iOS, pull requests merged in 2021-04, with the labels that each got.

#586 Allow customization of NUX button view shadows constraints
  WordPressAuthenticator.podspec
  WordPressAuthenticator/NUX/NUXButtonView.storyboard
  WordPressAuthenticator/NUX/NUXButtonViewController.swift
  WordPressAuthenticator/Signin/LoginPrologueViewController.swift
Labels: bug

#587 Merge release/1.36.0 to develop
  WordPressAuthenticator.podspec
Labels: releases

#590 Disable sending of the email if the enableSignUp isn't on
  WordPressAuthenticator.podspec
  WordPressAuthenticator/Unified Auth/View Related/Get Started/GetStartedViewController.swift
Labels: enhancement

#591 Fixes a styling issue.
  WordPressAuthenticator/Signin/LoginViewController.swift
Labels: bug

#592 Add the ability to customize the NUXButton styles on the Login Prologue
  WordPressAuthenticator.podspec
  WordPressAuthenticator/Authenticator/WordPressAuthenticatorStyles.swift
  WordPressAuthenticator/NUX/NUXButton.swift
  WordPressAuthenticator/NUX/NUXButtonViewController.swift
  WordPressAuthenticator/Signin/LoginPrologueViewController.swift
Labels: enhancement
