Repository wordpress-mobile/WordPressAuthenticator-iOS, pull requests merged in 2022-01, with the labels that each got.

#629 Remove 1password framework usage.
  Podfile
  Podfile.lock
  WordPressAuthenticator.podspec
  WordPressAuthenticator.xcodeproj/project.pbxproj
  WordPressAuthenticator/Authenticator/WordPressAuthenticator.swift
  WordPressAuthenticator/Extensions/UIImage+Assets.swift
  WordPressAuthenticator/Extensions/WPStyleGuide+Login.swift
  WordPressAuthenticator/NUX/NUXButton.swift
  WordPressAuthenticator/NUX/NUXKeyboardResponder.swift
  WordPressAuthenticator/NUX/NUXViewControllerBase.swift
  WordPressAuthenticator/NUX/WPWalkthroughTextField.m
  WordPressAuthenticator/Resources/Assets.xcassets/Contents.json
  WordPressAuthenticator/Resources/Assets.xcassets/onepassword-button.imageset/Contents.json
  WordPressAuthenticator/Resources/Assets.xcassets/onepassword-button.imageset/onepassword-button.pdf
  WordPressAuthenticator/Services/OnePasswordFacade.swift
  WordPressAuthenticator/Services/OnePasswordResultsFetcher.swift
  WordPressAuthenticator/Signin/AppleAuthenticator.swift
  WordPressAuthenticator/Signin/Login2FAViewController.swift
  WordPressAuthenticator/Signin/LoginEmailViewController.swift
  WordPressAuthenticator/Signin/LoginPrologueLoginMethodViewController.swift
  WordPressAuthenticator/Signin/LoginPrologueSignupMethodViewController.swift
  WordPressAuthenticator/Signin/LoginPrologueViewController.swift
  WordPressAuthenticator/Signin/LoginSelfHostedViewController.swift
  WordPressAuthenticator/Signin/LoginUsernamePasswordViewController.swift
  WordPressAuthenticator/Signin/LoginWPComViewController.swift
  WordPressAuthenticator/Unified Auth/StoredCredentialsAuthenticator.swift
  WordPressAuthenticator/Unified Auth/StoredCredentialsPicker.swift
  WordPressAuthenticator/Unified Auth/View Related/Get Started/GetStartedViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/Password/PasswordViewController.swift
  WordPressAuthenticator/Unified Auth/View Related/Reusable Views/GravatarEmailTableViewCell.swift
  WordPressAuthenticator/Unified Auth/View Related/Reusable Views/GravatarEmailTableViewCell.xib
  WordPressAuthenticator/Unified Auth/View Related/Reusable Views/TextFieldTableViewCell.swift
  WordPressAuthenticator/Unified Auth/View Related/Site Address/SiteCredentialsViewController.swift
  WordPressAuthenticatorTests/Authenticator/WordPressAuthenticatorTests.swift
  WordPressAuthenticatorTests/Mocks/MockOnePasswordFacade.swift
  WordPressAuthenticatorTests/Mocks/WordpressAuthenticatorProvider.swift
Labels: enhancement

#633 Merge 1.42.2 stable version bump into `trunk`
  WordPressAuthenticator.podspec
Labels: releases

#632 Improve error description
  WordPressAuthenticator.podspec
  WordPressAuthenticator/Services/WordPressXMLRPCAPIFacade.m
Labels: enhancement

#631 Match "Need more help" language
  WordPressAuthenticator.podspec
  WordPressAuthenticator/Services/WordPressXMLRPCAPIFacade.m
Labels: bug
