Repository wordpress-mobile/WordPressAuthenticator-iOS, pull requests merged in 2024-11, with the labels that each got.

#860 [Tooling] SwiftLint: Use `linter` agent instead of `default` agent
  .buildkite/pipeline.yml
Labels: tooling

#858 Allow login for WPCOM suspended sites
  CHANGELOG.md
  WordPressAuthenticator/Authenticator/WordPressAuthenticatorConfiguration.swift
  WordPressAuthenticator/Model/WordPressComSiteInfo.swift
  WordPressAuthenticator/Services/WordPressComBlogService.swift
  WordPressAuthenticator/Unified Auth/View Related/Site Address/SiteAddressViewController.swift
Labels: enhancement

#861 Add support for requesting account creation when sending auth magic link
  CHANGELOG.md
  Gemfile.lock
  Podfile
  Podfile.lock
  WordPressAuthenticator.podspec
  WordPressAuthenticator/Services/WordPressComAccountService.swift
Labels: enhancement

#866 Release version 9.10.1
  CHANGELOG.md
  Podfile.lock
  WordPressAuthenticator.podspec
Labels: releases
